### ISSUE TITLE
Build entire App

### ISSUE THREAD

**Issue by bilicio** [alber70g/electron-hyperapp-feathers#1]
Hi Albert!

Can you show how to build this entire app? 
Im struggling putting all dependecies together and the app runs blank when i compile it.

thank you!!

**Comment by alber70g** [comment]
Thanks for taking time to use this.

I believe the version of Hyperapp isn't compatible anymore. That's why you get nothing. I'll look into it and see if I can update it to the latest version

**Comment by alber70g** [comment]
I just did a fresh clone, `yarn install` and `yarn start`, and I have no problem running it. Could you be more specific about the error you get?

**Comment by alber70g** [comment]
I changed the `yarn install` and `yarn start` command to include electron. `start` will launch the app immediately.

**Comment by bilicio** [comment]
Hi Albert! thank you! running its ok.. what im trying to do is package everything together. I could package the react with ELECTRON and feathers backend separated with PKG. Do you have any tips to package everything together? :)

**Comment by alber70g** [comment]
I see. Well it's not really used that way, so I'm afraid I don't have a quick solution. You might want to look somewhere else for that. It might be better to look for other solutions to incorporate a 'backend' like feathersjs into an electron app.
